### PR TITLE
Add foreground color to non-emoji glyphs

### PR DESCRIPTION
**Pull request by david-higgins**
I've just added this in, sending back the love.

### CODE REVIEW

**Comment by samhocevar** [comment]
Thanks, especially for the last commit! I’m not familiar enough with WPF to come up with such patterns.

**Comment by samhocevar** [comment]
Actually, the pattern change in 72974da is invalid for `TextProperty`, because `Inlines.Clear()` will modify `Text`. Even if there is a recursion guard in our `OnTextChanged`, there is no guard against *other* callbacks registered for `base.TextProperty` being called. This is why I chose to completely reimplement `TextProperty`. I shall revert this specific change.

You can trigger the bug by running the `FontViewer` project in the solution.

**Comment by samhocevar** [comment]
Update on this: it seems that overriding the `CoerceText` callback is actually enough.

**Comment by david-higgins** [comment]
Glad I can help! I didn't spot that bug but it seems you have a workaround :). 

Maybe a better solution would be to subclass a UserControl that contains a private TextBlock, that way it's possible to create dependencyproperties on the usercontrol like Text,Color, do the processing when they change and update the internal textblock just once?

**Comment by samhocevar** [comment]
At some point it [was exactly like you suggest](https://github.com/samhocevar/emoji.wpf/blob/6b9490ac9c879cd90eed9ffa4ac421a6a9f1e151/Emoji.Wpf/TextBlock.cs), but the number of properties I had to proxy (`Text`, `FontSize`, `TextAlignment`, `FontFamily`, etc.) made me [switch to inheritance instead](https://github.com/samhocevar/emoji.wpf/commit/892dd5bee3d80604647f375b003034c70dcc8fe6#diff-72c93653033abb50998b36e7ad7e10fe). The code was starting to get a bit large for what it was actually doing.

**Pull request merged**
